#!/bin/bash
### Main program
### Thanks to LuckyCyborg for the adjustments
### Switch between Light / Dark theme during the day 

KDE_CONF_DIR="/home/$USER/.config"
LOOK=$(cat ${KDE_CONF_DIR}/kdeglobals | awk -F'=' '/LookAndFeelPackage/,$0=$2')
NOW=$(date +%H%M)

if [ -r /etc/lookandfeel.conf ]; then
  . /etc/lookandfeel.conf
fi

COUNT=300

while [ "$NOW" -lt "2359" ] ; do
  if [ "$COUNT" -lt "300" ] ; then
    COUNT=$((COUNT+1))
    sleep 1
    continue;
  fi
  COUNT=0
  
  START=${START:-0800}
  END=${END:-2000}

  if [ "$NOW" -lt "$END" ] && [ "$NOW" -gt "$START" ] ; then
    if [ "$LOOK" != "$DAY_THEME" ] ; then
      lookandfeeltool --apply "$DAY_THEME" >/dev/null 2>&1
      notify-send "Look & Feel" "Day Theme : On"
    fi
  else 
    if [ "$LOOK" != "$NIGHT_THEME" ] ; then
      lookandfeeltool --apply "$NIGHT_THEME" >/dev/null 2>&1
      notify-send "Look & Feel" "Night Theme : On"
    fi
  fi
  LOOK=$(cat ${KDE_CONF_DIR}/kdeglobals | awk -F'=' '/LookAndFeelPackage/,$0=$2')
  NOW=$(date +%H%M)
done

